import { StyleSheet } from 'react-native';
import { Colors, Typography } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.surfacePrimary,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetBackground: {
    backgroundColor: Colors.surfacePrimary,
    borderTopWidth: 1,
    borderTopColor: Colors.borderSubtle,
  },
  handleIndicator: {
    width: 32,
    height: 3,
    backgroundColor: Colors.textTertiary,
  },
  sheetContent: {
    paddingHorizontal: 24,
    paddingTop: 8,
    flex: 1,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 16,
  },
  backButton: {
    padding: 4,
    marginLeft: -4,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surfaceTertiary,
    height: 52,
    borderRadius: 12,
    paddingHorizontal: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: Colors.borderSubtle,
  },
  searchIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.accent,
    marginRight: 16,
  },
  searchText: {
    ...Typography.body,
    fontWeight: '500',
    color: Colors.textSecondary,
    fontFamily: 'JetBrainsMono_500Medium',
  },
  quickActions: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  quickPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surfaceTertiary,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
  },
  quickPillText: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'JetBrainsMono_500Medium',
  },
  recentSection: {
    marginTop: 8,
  },
  recentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  recentIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.surfaceTertiary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  recentTitle: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 2,
    fontFamily: 'JetBrainsMono_500Medium',
  },
  recentSubtitle: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontFamily: 'JetBrainsMono_500Medium',
  },
  divider: {
    height: 1,
    backgroundColor: Colors.borderSubtle,
    marginVertical: 8,
  },
  searchInputsContainer: {
    paddingHorizontal: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderSubtle,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchConnectionLine: {
    position: 'absolute',
    left: 27,
    top: 24,
    width: 1,
    height: 20,
    backgroundColor: Colors.borderSubtle,
    zIndex: -1,
  },
  locationInput: {
    flex: 1,
    height: 40,
    color: Colors.textPrimary,
    fontSize: 16,
  },
  locationInputActive: {
    backgroundColor: Colors.surfaceTertiary,
    borderRadius: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: Colors.borderActive,
  },
  sectionLabel: {
    ...Typography.caption,
    color: Colors.textTertiary,
    marginBottom: 16,
    marginTop: 8,
  },
  distanceText: {
    fontFamily: 'JetBrainsMono_500Medium',
    color: Colors.textTertiary,
    fontSize: 12,
  },
  routeSummaryText: {
    color: Colors.textSecondary,
    fontSize: 14,
    flex: 1,
    textAlign: 'center',
    fontFamily: 'JetBrainsMono_500Medium',
  },
  etaBadge: {
    fontFamily: 'JetBrainsMono_500Medium',
    color: Colors.textPrimary,
    fontSize: 14,
    backgroundColor: Colors.surfaceTertiary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  rideCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.surfaceSecondary,
    borderWidth: 1,
    borderColor: Colors.borderSubtle,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  rideCardSelected: {
    backgroundColor: Colors.surfaceTertiary,
    borderColor: Colors.borderActive,
  },
  rideCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rideName: {
    color: Colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 2,
    fontFamily: 'JetBrainsMono_500Medium',
  },
  rideDesc: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontFamily: 'JetBrainsMono_500Medium',
  },
  ridePrice: {
    fontFamily: 'JetBrainsMono_500Medium',
    color: Colors.textPrimary,
    fontSize: 16,
  },
  aiBanner: {
    backgroundColor: Colors.surfaceTertiary,
    borderLeftWidth: 2,
    borderLeftColor: Colors.accent,
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
  },
  aiBannerText: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontFamily: 'JetBrainsMono_500Medium',
  },
  primaryCta: {
    backgroundColor: Colors.accent,
    borderRadius: 14,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryCtaText: {
    color: Colors.surfacePrimary,
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.3,
    fontFamily: 'JetBrainsMono_500Medium',
  },
  matchingHeading: {
    ...Typography.headingL,
    color: Colors.textPrimary,
    marginTop: 16,
    fontFamily: 'JetBrainsMono_500Medium',
  },
  matchingSubtext: {
    color: Colors.textTertiary,
    fontSize: 14,
    marginTop: 16,
    fontFamily: 'JetBrainsMono_500Medium',
  },
  dotContainer: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
  },
  pulseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.accent,
  },
  cancelGhostBtn: {
    marginTop: 24,
    alignSelf: 'flex-start',
  },
  cancelGhostText: {
    color: Colors.destructive,
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'JetBrainsMono_500Medium',
  },
  assignedTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  driverProfileGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  driverAvatarFallback: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.surfaceTertiary,
    borderWidth: 1,
    borderColor: Colors.borderActive,
    justifyContent: 'center',
    alignItems: 'center',
  },
  driverName: {
    color: Colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'JetBrainsMono_500Medium',
  },
  driverRating: {
    fontFamily: 'JetBrainsMono_500Medium',
    color: Colors.textSecondary,
    fontSize: 12,
  },
  etaLarge: {
    fontFamily: 'JetBrainsMono_500Medium',
    color: Colors.accent,
    fontSize: 28,
  },
  vehicleDetailsText: {
    color: Colors.textSecondary,
    fontSize: 12,
    marginTop: 4,
    fontFamily: 'JetBrainsMono_500Medium',
  },
  actionCircleRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 24,
  },
  actionCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.surfaceTertiary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  evBadgePill: {
    backgroundColor: "transparent",
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 120,
    marginBottom: 16,
    borderColor: Colors.accent,
    borderWidth: 1,
  },
  evBadgeText: {
    color: "white",
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'JetBrainsMono_500Medium',
  },
  secondaryBtn: {
    width: '100%',
    height: 56,
    backgroundColor: Colors.surfaceTertiary,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  secondaryBtnText: {
    color: Colors.textPrimary,
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'JetBrainsMono_500Medium',
  },
  inProgressTrackContainer: {
    height: 4,
    backgroundColor: Colors.surfaceTertiary,
    borderRadius: 2,
    width: '100%',
    marginTop: 8,
    overflow: 'hidden',
  },
  inProgressTrackFill: {
    height: '100%',
    width: '65%', // Mock progress
    backgroundColor: Colors.accent,
    borderRadius: 2,
  },
  successCircleLarge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: Colors.success,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 214, 143, 0.1)',
  },
  fareBreakdownCard: {
    backgroundColor: Colors.surfaceSecondary,
    width: '100%',
    padding: 24,
    borderRadius: 16,
    marginTop: 24,
    borderWidth: 1,
    borderColor: Colors.borderSubtle,
  },
  fareRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderSubtle,
  },
  primaryCtaDone: {
    width: '100%',
    height: 56,
    backgroundColor: Colors.accent,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryCtaDoneText: {
    fontFamily: 'JetBrainsMono_500Medium',
    color: Colors.surfacePrimary,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.3,
  }
});
